# This workflow is designed to verify the code follows basic best practices, perform unit tests.

name: Python 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with pylint
      run: |
        # stop the build if pylint is 10 for everything
        pylint easydb
        pylint tests

    - name: Lint with mypy
      run: |
        # stop the build if pylint is 10 for everything
        mypy easydb
        mypy tests
    - name: Unit Test with pytest
      run: |
        pytest tests

    - name: Build the stack
      run: docker-compose up -d

    - name: Intergration Test with pytest
      run: |
         pytest tests
      env:
        INTEGRATION_TEST: True
        POSTGRES_PASSWORD: testing1234
        POSTGRES_USER: testing1234
        POSTGRES_DB: testing1234
        DB_IP_ADDRESS: 127.0.0.1

    - name: PyCharm Python Security Scanner
      uses: tonybaloney/pycharm-security@1.20.1
    


